name: build and upload to Google cloud strage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Cache Directory
        run: mkdir -p ~/cache

      - name: Cache Directory
        id: cache
        uses: actions/cache/@v3
        with:
          path: ~/cache
          key: cache-${{ runner.os }}

      - name: Pull Docker Image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker pull paperist/texlive-ja:latest
          docker save -o ~/cache/texlive.tar paperist/texlive-ja:latest

      - name: Load Docker Image
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load -i ~/cache/texlive.tar

      - name: Build LaTeX
        run: make build

      - name: archive artifacts
        run: |
          mkdir -p artifacts
          cp ./out/report.pdf ./artifacts/report.pdf
          cp ./report.tex ./artifacts/report.tex
          cp ./ref.bib ./artifacts/ref.bib

      - name: echo
        run: echo "projects/${{ secrets.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ secrets.POOLNAME }}/providers/${{ secrets.PROVIDER_NAME }}"

      - name: auth gcp
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: "projects/${{ secrets.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ secrets.POOLNAME }}/providers/${{ secrets.PROVIDER_NAME }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT_NAME }}@${{ secrets.PROJECT_NAME }}.iam.gserviceaccount.com"

      - name: Use gcloud CLI
        run: 'gcloud storage cp -r ./artifacts gs://graduation-thesis'

